channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - requests
      - openpyxl
      - selenium
      - robotframework
      - robotframework-seleniumlibrary
      - rpaframework  
